[package]
name = "fileSync"
version = "0.1.0"
authors = ["black616angel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.2"
ftp = { version = "3.0.1", features = [ "secure" ] }
#mysql = "*"
diesel = { version = "1.4.4", features = ["mysql"] }
dotenv = "*"
